// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN6K2OaNaa80EBNBRTRYgRgHVpvRztA1w',
    appId: '1:903861198720:web:ca9c189d39bde274baeb65',
    messagingSenderId: '903861198720',
    projectId: 'cherryblock-c0113',
    authDomain: 'cherryblock-c0113.firebaseapp.com',
    storageBucket: 'cherryblock-c0113.firebasestorage.app',
    measurementId: 'G-XHSQVE5SMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6PuqN74vxkay7bXwqakp1JS7Vw4toRBs',
    appId: '1:903861198720:android:e99d2f6153b6cc2bbaeb65',
    messagingSenderId: '903861198720',
    projectId: 'cherryblock-c0113',
    storageBucket: 'cherryblock-c0113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTz06TqJjAoSk-vDXTGbHxbON8yf23qyo',
    appId: '1:903861198720:ios:6067e68a06306689baeb65',
    messagingSenderId: '903861198720',
    projectId: 'cherryblock-c0113',
    storageBucket: 'cherryblock-c0113.firebasestorage.app',
    iosClientId: '903861198720-51ctc18894r82m0nj0f2n8dd4rio42i6.apps.googleusercontent.com',
    iosBundleId: 'com.example.cherryBlock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTz06TqJjAoSk-vDXTGbHxbON8yf23qyo',
    appId: '1:903861198720:ios:6067e68a06306689baeb65',
    messagingSenderId: '903861198720',
    projectId: 'cherryblock-c0113',
    storageBucket: 'cherryblock-c0113.firebasestorage.app',
    iosClientId: '903861198720-51ctc18894r82m0nj0f2n8dd4rio42i6.apps.googleusercontent.com',
    iosBundleId: 'com.example.cherryBlock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN6K2OaNaa80EBNBRTRYgRgHVpvRztA1w',
    appId: '1:903861198720:web:497e34b71f726aaebaeb65',
    messagingSenderId: '903861198720',
    projectId: 'cherryblock-c0113',
    authDomain: 'cherryblock-c0113.firebaseapp.com',
    storageBucket: 'cherryblock-c0113.firebasestorage.app',
    measurementId: 'G-C4Y6X3RZJT',
  );
}
